CREATE TABLE `otpVerifications` (
	`id` varchar(64) NOT NULL,
	`phone` varchar(20) NOT NULL,
	`code` varchar(6) NOT NULL,
	`isVerified` boolean NOT NULL DEFAULT false,
	`attempts` int NOT NULL DEFAULT 0,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp DEFAULT (now()),
	CONSTRAINT `otpVerifications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `questionnaireResponses` (
	`id` varchar(64) NOT NULL,
	`userId` varchar(64) NOT NULL,
	`businessPurpose` text,
	`productStage` varchar(50),
	`activeUsers` varchar(50),
	`sixMonthGoals` json,
	`hasDeadlineOrInvestment` boolean,
	`deadlineOrInvestmentDetails` text,
	`teamStructure` varchar(50),
	`totalProfessionals` int,
	`teamProfiles` json,
	`dedicationType` varchar(50),
	`fattoRole` varchar(50),
	`fattoEntryPoint` varchar(50),
	`requirementsProcess` varchar(50),
	`plannedFeatures` int,
	`validationMethod` varchar(50),
	`mainTechnologies` text,
	`systemsCount` int,
	`architectureModel` varchar(50),
	`architectureAutonomy` varchar(50),
	`externalIntegrations` int,
	`hasCriticalIntegrations` boolean,
	`criticalIntegrationsDetails` text,
	`environments` json,
	`environmentsCount` int,
	`provisioningResponsible` varchar(50),
	`cicdImplemented` varchar(50),
	`deliveryTools` json,
	`monthlyDeploys` int,
	`fattoDeployResponsibility` varchar(50),
	`fattoSustainment` boolean,
	`monthlyIncidents` int,
	`currentSupport` varchar(50),
	`slaDuration` varchar(50),
	`releaseRoadmap` varchar(50),
	`meetingFrequency` varchar(50),
	`regularMeetingParticipants` int,
	`hasProductOwner` boolean,
	`backlogTools` varchar(50),
	`decisionFormalization` varchar(50),
	`contractModel` varchar(50),
	`billingType` varchar(50),
	`startTimeline` varchar(50),
	`budgetRange` varchar(50),
	`requiredProfessionals` int,
	`previousVendors` boolean,
	`vendorCount` int,
	`mainDifficulties` json,
	`lessonsLearned` text,
	`expectedFattoRole` json,
	`prioritaryDeliverables` json,
	`shortTermDeliverables` int,
	`expectedFattoAutonomy` varchar(50),
	`analystNotes` text,
	`currentStep` int NOT NULL DEFAULT 0,
	`isCompleted` boolean NOT NULL DEFAULT false,
	`completedAt` timestamp,
	`createdAt` timestamp DEFAULT (now()),
	`updatedAt` timestamp DEFAULT (now()),
	CONSTRAINT `questionnaireResponses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `phone` varchar(20);--> statement-breakpoint
ALTER TABLE `users` ADD CONSTRAINT `users_email_unique` UNIQUE(`email`);